id: IA21DFD9C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T18:24:11+00:00'
last_modified: '2022-06-08T14:30:18.686828+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG14733
  title: ལ་གཞས་རྩེད་སྐོར་བཅུ་གཉིས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A83E:
      image_group_id: I2PD17899
      title: ''
      total_pages: 290
      order: 1
      base_file: A83E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
