id: P010561
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG14733
  title: ལ་གཞས་རྩེད་སྐོར་བཅུ་གཉིས།
  author: ''
  volumes:
    e324e0f0712e4d99b64d033e0d171437:
      image_group_id: I2PD17899
      title: ''
      volume_number: 1
      total_pages: 290
      base_file: v001.txt
